# AT-bot Documentation Build Configuration
# Controls which files and directories are included/excluded from documentation builds

# Exclude patterns (glob patterns, one per line)
# Files matching these patterns will NOT be included in documentation builds
exclude:
  # Hidden directories (copilot instructions, VSCode config, etc)
  - .github/**
  - .vscode/**
  - .idea/**
  - .git/**
  
  # Copilot and AI instructions (not user documentation)
  - "**/*copilot-instructions*"
  - "**/*agents-instructions*"
  
  # Development/tooling files
  - node_modules/**
  - dist/**
  - coverage/**
  - .npm/**
  - .DS_Store
  
  # Build artifacts and compiled outputs
  - mcp-server/dist/**
  - mcp-server/node_modules/**
  - mcp-server/coverage/**
  
  # Temporary files
  - "*.tmp"
  - "*.log"
  - "*~"
  - ".swp"
  - ".swo"
  
  # Session-specific/transient docs (keep but don't include in main build)
  - doc/sessions/**
  - doc/progress/**
  
  # Test files (reference code, not user docs)
  - tests/**
  - "**/*.test.sh"
  - "**/*.spec.ts"

# Include patterns (explicit list of what to include)
# If specified, ONLY files matching these patterns will be included
# This is an allowlist approach - everything else is excluded unless listed here
# 
# Build order is important for PDF generation:
# 1. TOC (near beginning)
# 2. Main/core docs (middle)
# 3. API reference (end/appendix)
include:
  # ==================== FRONT MATTER ====================
  # Cover page and preamble (very first)
  - doc/COVER.md
  
  # Table of Contents (generated, placed after cover)
  - doc/TOC.md
  
  # ==================== CORE PROJECT DOCS ====================
  # Core project documentation
  - README.md
  - PLAN.md
  - AGENTS.md
  - STYLE.md
  - SECURITY.md
  - TODO.md
  - LICENSE
  - CONTRIBUTING.md
  
  # ==================== USER & DEVELOPER GUIDES ====================
  # Feature and implementation documentation (main docs)
  - doc/QUICKSTART.md
  - doc/QUICKREF.md
  - doc/CONFIGURATION.md
  - doc/ENVIRONMENT_VARIABLES.md
  - doc/FAQ.md
  - doc/DEBUG_MODE.md
  - doc/ENCRYPTION.md
  - doc/ARCHITECTURE.md
  - doc/DOCUMENTATION.md
  - doc/TESTING.md
  - doc/TESTING_GUIDE.md
  - doc/PACKAGING.md
  - doc/EXAMPLES.md
  
  # MCP documentation
  - mcp-server/README.md
  - mcp-server/docs/QUICKSTART_MCP.md
  - mcp-server/docs/MCP_INTEGRATION.md
  - mcp-server/docs/MCP_TOOLS.md
  
  # ==================== EXAMPLES ====================
  - doc/examples/**/*.sh
  - doc/examples/**/*.bash
  
  # ==================== SOURCE REFERENCE ====================
  # Source code for reference (optional)
  - lib/atproto.sh
  - lib/config.sh
  - lib/cli-utils.sh
  - bin/at-bot
  
  # Scripts and tools
  - scripts/install-completions.sh
  - Makefile
  - install.sh
  
  # ==================== APPENDIX ====================
  # API Reference (placed at end as appendix)
  - doc/API.md

# Output configuration
output:
  # Output format (html, markdown, pdf, etc.)
  format: pdf
  
  # Output directory relative to project root
  directory: dist/docs
  
  # Generate table of contents
  toc: true
  
  # Generate index
  index: true
  
  # Navigation structure
  generate_nav: true
  
  # Theme/styling
  theme: default
  
  # CSS file for custom styling (optional)
  css: null

# Build options
build:
  # Include file metadata (timestamps, file paths, etc.)
  include_metadata: true
  
  # Generate code syntax highlighting
  syntax_highlighting: true
  
  # Include examples and code snippets
  include_examples: true
  
  # Verbose output during build
  verbose: false
  
  # Generate sitemap
  generate_sitemap: true
  
  # Clean output directory before building
  clean_before_build: true

# Search and indexing
search:
  # Enable full-text search index generation
  enabled: true
  
  # Searchable fields
  fields:
    - title
    - content
    - keywords

# Analytics (optional)
analytics:
  enabled: false
  google_analytics_id: null

# Metadata
metadata:
  # Project name
  project_name: AT-bot
  
  # Project title (used in cover page and headers)
  title: "AT Protocol Bot — Minimal MCP bridge"
  
  # Project description
  description: "A simple CLI tool for Bluesky AT Protocol automation"
  
  # Version (can be read from package.json or set manually)
  version: "1.0"
  
  # Author
  author: "Kara Rawson {rawsonkara@gmail.com}, et al."
  
  # License
  license: "CC0 1.0 Universal (Public Domain)"
  
  # Repository URL
  repository: "https://github.com/p3nGu1nZz/atproto"
