#!/bin/bash
# Debug Mode Test - Shows how DEBUG mode displays plaintext passwords

echo "================================"
echo "AT-bot DEBUG Mode Demo"
echo "================================"
echo ""
echo "This demonstrates the DEBUG mode that shows plaintext passwords."
echo "Set DEBUG=1 to enable debug output."
echo ""
echo "Example usage:"
echo "  DEBUG=1 at-bot login"
echo ""
echo "Debug output will show:"
echo "  - Password entered (with length)"
echo "  - Password in plaintext"
echo "  - Password in base64"
echo "  - All credential operations"
echo ""
echo "To test with saved credentials:"
echo "  DEBUG=1 at-bot login  # Shows password loading"
echo ""
echo "⚠️  WARNING: Only use DEBUG=1 in secure environments!"
echo "    Debug mode will print passwords to the terminal."
echo ""
